version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dj-quotes
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: quotes-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=258456
      - POSTGRES_DB=quotes_db
    ports:
      - 5432:5432